name : Application Deploying on AWS

on:
  workflow_dispatch

jobs:
  working-job:
    runs-on: ubuntu-latest

    steps:
      - name : Echo Message
        run : echo "Application Deployed on AWS successfully ✅"