name : Smoke Testing for infra and Networking

on:
  workflow_call:

jobs:
  working-job:
    runs-on: ubuntu-latest

    steps:
      - name : Echo Message
        run : echo "Smoke Test runs successfully ✅"